version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - mynetwork
  kafka:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork
  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - mynetwork

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: [ "bash", "./wait-for-it.sh", "kafka", "9092", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - kafka
    networks:
      - mynetwork

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    ports:
      - "8001:6379"
    networks:
      - mynetwork

  stock-service:
    build: ./stock
    image: stock:latest
    command: [ "bash", "./wait-for-it.sh", "kafka", "9092", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
      - kafka
    networks:
      - mynetwork

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - mynetwork

  payment-service:
    build: ./payment
    image: user:latest
    command: [ "bash", "./wait-for-it.sh", "kafka", "9092", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
      - kafka
    networks:
      - mynetwork

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - mynetwork
  
  order-cluster-node-0:
    image: redis:7.2-bookworm
    command: redis-server --port 7006 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
    ports:
      - "7006:7006"
    networks:
      - mynetwork

  order-cluster-node-1:
    image: redis:7.2-bookworm
    command: redis-server --port 7001 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:7001"
    networks:
      - mynetwork
  
  order-cluster-node-2:
    image: redis:7.2-bookworm
    command: redis-server --port 7002 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:7002"
    networks:
      - mynetwork
  
  order-cluster-node-3:
    image: redis:7.2-bookworm
    command: redis-server --port 7003 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:7003"
    networks:
      - mynetwork
  
  order-cluster-node-4:
    image: redis:7.2-bookworm
    command: redis-server --port 7004 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:7004"
    networks:
      - mynetwork
  
  order-cluster-node-5:
    image: redis:7.2-bookworm
    command: redis-server --port 7005 --requirepass redis --masterauth redis --maxmemory 512mb --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:7005"
    networks:
      - mynetwork
  
  order-cluster-creator:
    image: redis:7.2-bookworm
    container_name: redis-cluster-creator
    command: redis-cli -a redis -p 7006 --cluster create order-cluster-node-0:7006 order-cluster-node-1:7001 order-cluster-node-2:7002 order-cluster-node-3:7003 order-cluster-node-4:7004 order-cluster-node-5:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - order-cluster-node-0
      - order-cluster-node-1
      - order-cluster-node-2
      - order-cluster-node-3
      - order-cluster-node-4
      - order-cluster-node-5
    ports:
      - "6999:6999"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
