version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - mynetwork
  kafka:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork
  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - mynetwork

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: [ "bash", "./wait-for-it.sh", "kafka", "9092", "--", "gunicorn", "-b", "0.0.0.0:5000", "-w", "2", "--timeout", "30", "--log-level=info", "app:app" ]
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - kafka
    networks:
      - mynetwork

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - mynetwork

  stock-service:
    build: ./stock
    image: stock:latest
    command: ["bash", "./wait-for-it.sh", "kafka", "9092", "--", "gunicorn", "-b", "0.0.0.0:5000", "-w", "2", "--timeout", "30", "--log-level=info", "app:app"]
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
      - kafka
    networks:
      - mynetwork

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - mynetwork

  payment-service:
    build: ./payment
    image: user:latest
    command: [ "bash", "./wait-for-it.sh", "kafka", "9092", "--", "gunicorn", "-b", "0.0.0.0:5000", "-w", "2", "--timeout", "30", "--log-level=info", "app:app" ]
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
      - kafka
    networks:
      - mynetwork

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
